# This is a basic workflow to help you get started.
# It will take the following action whenever a push is made to the "main" branch.
on:
  push:
    branches:
    - main

env:
  SERVER: mail.minepos.net
  DOMAIN: testnodejs.aubury.me
  USER_TSH: myrthe.dullaart

jobs:
  demo:
    permissions:
      id-token: write
      contents: read
    name: example
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Fetch Teleport binaries
      uses: teleport-actions/setup@v1
      with:
        version: 15.3.0
    - name: Fetch credentials using Machine ID
      id: auth
      uses: teleport-actions/auth@v2
      with:
        proxy: teleport.andrewa.co.uk:443
        token: github_md-bot
        certificate-ttl: 1h
    - name: Stop project running (PM2)
      run: tsh ssh $USER_TSH@$SERVER "pm2 stop $DOMAIN  || :"
    - name: Deploy code to server
      run: tsh scp -r * $USER_TSH@$SERVER:/home/$USER_TSH/web/$DOMAIN/public_html
    - name: Start project running (PM2)
      run: tsh ssh $USER_TSH@$SERVER "cd /home/$USER_TSH/web/$DOMAIN/public_html; pm2 start --name $DOMAIN index.js"
    - name: Ensure Socket perms
      run: tsh ssh $USER_TSH@$SERVER "sleep 1; cd /home/$USER_TSH/web/$DOMAIN/; chmod 666 server.socket"

